### ISSUE TITLE
[BUG]:  dellemc.powerstore.cluster does not create cluster

### ISSUE THREAD

**Issue by jason-technology** [dell/ansible-powerstore#33]
Running cluster create task does not initiate cluster creation.  Nothing happens on the array.  Ansible reports success immediately, even though set to synchronous.
All other modules are working fine / not a config error.
API call with the same parameters results in cluster creation.
Link_local_address is correct.
Latest PyPowerstore
Latest powerstore galaxy collection
Newly shipped arrays.

- name: Create Cluster
      dellemc.powerstore.cluster:
        array_ip: "{{ array_ip }}"
        user: "{{ user }}"
        password: "{{ password }}"
        verifycert: false
        ignore_network_warnings: true
        cluster_name: "{{ cluster_name }}"
        appliances:
          - link_local_address: "{{ link_local }}"
            name: "{{ appliance_name }}"
            drive_failure_tolerance_level: "{{ drive_failure_tolerance }}"
        dns_servers:
          - "{{ dns1 }}"
          - "{{ dns2 }}"
        ntp_servers:
          - "{{ ntp1 }}"
          - "{{ ntp2 }}"
        networks:
          - type: "Management"
            vlad_id: 0
            prefix_length: "{{ mgmt_ip_prefix }}"
            gateway: "{{ gateway_ip }}"
            cluster_mgmt_address: "{{ cluster_ip }}"
            addresses:
              - "{{ appliance_ip }}"
              - "{{ node_a_ip }}"
              - "{{ node_b_ip }}"
        is_http_redirect_enabled: true
        wait_for_completion: true
        state: "present"
      register: create_cluster_output
      tags:
        - create_cluster

**Comment by anupamaloke** [comment]
@jason-technology , thank you for reporting the issue. We will be investigating this and accordingly address this in future release.

**Comment by Bhavneet-Sharma** [comment]
Hi @jason-technology ,
I can see here, you have not given the validate_create flag (reference: https://github.com/dell/ansible-powerstore/blob/main/plugins/modules/cluster.py#L291). So by default, this flag is passed as True and then it will follow the validate create cluster workflow. Hence you were getting success immediately because the module is executing the validate create cluster operation.
Please give it a try with **validate_create: false** . 
sample playbook would be like this:

![image](https://github.com/dell/ansible-powerstore/assets/91545772/d5280a6f-d3f5-4dff-a352-aec84c4ea922)

It is recommended to use the Async call (using this flag as `wait_for_completion: false` ) to perform the create cluster operation as it takes more than 15 to 30 minutes. This will generate the job ID. You can use the Job to track the deployment status of the cluster using **job_id**.

Please check the module documentation for each parameter usage and Let us know if you need further information.

**Comment by anupamaloke** [comment]
@jason-technology, I am closing this issue. Please feel free to open a new one if you are still running into this issue.
